/**
 * 
 */
package code;

import processing.core.PApplet;

/**
 * The main class to start your Scene.
 * <p>
 * It is strongly recommended that you do NOT edit this file.  
 * @author
 * @version 1.0.0
 */
public class Main {

	/**
	 * main method called when first running the Framework.
	 * <p>
	 * Creates an instance of {@link MyScene}, which is where all your code should be created.
	 * @see MyScene
	 * @param args Command line arguments
	 */
	public static void main(String[] args) {
		String[] a = {"MAIN"};
        PApplet.runSketch(a, new MyScene());
	}

}